// app/layout.tsx
import type { Metadata } from "next";
import "../globals.css";
import { NavBar } from "../components/NavBar"; 
import { SidebarProvider, SidebarTrigger } from "../../components/ui/sidebar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex bg-gray-100">
        <SidebarProvider>
          <NavBar />
            <SidebarTrigger />
            <main className="flex-1 h-screen overflow-y-auto transition-all duration-300">
              {children}
            </main>
        </SidebarProvider>
      </body>
    </html>
  );
}